#+TITLE: Phase 2 process for Outreach Internship Program
#+AUTHOR: VLEAD
#+DATE: [2018-09-26 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document details about the phase 2 process for the
  outreach remote intership program. This process would be
  followed by phase 3 after the students fix the issues for
  the IIIT H labs. Based on the fix, it would be reviewed by
  the VLEAD team and accepted/rejected.

* Motivation
  This internship program is conducted to motivate students
  from the Nodal center colleges to contribute towards this
  mission mode project run by MHRD. Students would be
  contributing towards the open source development community
  as well as improve the Virtual Labs. The motivation for us
  behind conducting such internship program is to do
  outreach activities for the Virtual Labs and improve its
  reach to as many colleges as possible.

* Process
** Phase 1 - Bug fixing process
   [[https://github.com/vlead/2018-outreach-remote-internship/blob/develop/src/phase1/validation-%26-review/docs/phase1-process.org][Link for the document]]

* Logistics

* Fallback plans

* Conclusion
  The labs would be improved as part of this program giving us an edge
  in outreach programs by connecting to the different Nodal
  Coordinators across the state.
  
