#+TITLE: Outreach Intership Program 
#+AUTHOR: VLEAD
#+DATE: [2018-04-17 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Draft e-mail for Boot Camp
  Dear Student,

  Greetings from Virtual Labs @ IIIT - Hyderabad!
  
  Keeping in view that students need some assistance for proceeding further in phase 2 process, we are conducting a one day Boot camp on 28th October, 2018 at IIITH campus.
  
  Agenda of the Boot camp:
  10:00 AM - Introduction to Virtual Labs
  10:30 AM - Tea break
  10:45 AM - Introduction to Git
  11:45 AM - Overview on HTML
  12:45 PM - Lunch Break
  01:45 PM - Overview on JavaScript
  03:30 PM - Tea Break
  03:45 PM - Overview on Phase 2 Process
  04:15 PM - Q&A Session 
  
  Date of Boot Camp :
  28th October, 2018 (Sunday).
  
  Timings of the Boot Camp :
  10:00 AM to 05:00PM
  
  Venue :
  Himalaya 205,
  IIIT-Hyderabad campus,
  Gachibowli,
  Hyderabad - 500032.
  
  Prerequisites:
  - Students should to carry their own laptops.
  - Git Bash should to be installed in the system if you are
    using Windows operating system.
  - Snacks will be provided. We request students to make
    their own lunch arrangements.

  Please confirm your presence at the Boot Camp by 27th
  October, 2018 before 09:00 AM.

  For any doubts or clarifications needed please feel free
  to contact us @ internship@vlabs.ac.in
  
  Thanks and Regards,

  Virtual Labs Team.
