#+TITLE: Phase 2 : Fixing and Validation of issues in Virtual Labs
#+AUTHOR: VLEAD
#+DATE: [2018-04-25 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the process to be followed by the
  interested students who wish to work for Virtual Labs
  remote internship and contribute to the open source
  community like GitHub.
* Process
  The Phase2 of the internship includes 2 parts.
  + Part 1 : Fixing an issues/bugs in the [[https://github.com/virtual-labs/][Virtual Labs]]
    repository.
  + Part 2 : Validating a fixed issue. 

* Link for lab code repositories
  Please use this [[https://github.com/virtual-labs/][link]] for the IIIT Hyderabad lab code
  repositories for the issues. The IIIT Hyderabad labs which
  needs to be fixed would have a naming convention of
  <labname>-iiith. Please go through all the repos existing
  here. You are free to pick up any issues to fix. 

* Steps to be followed for picking and fixing an issue
  + Step 1 - Choose a lab for which you want to start
    resolving the issues. Select the lab repository from
    [[https://github.com/virtual-labs/][Virtual Labs]].
  + Step 2 - [[https://help.github.com/articles/fork-a-repo/][Fork]] the lab repository so that you have the
    local copy of the lab codebase in your machine.
  + Step 3 - Go back to the main repository of the Virual
    Labs you  have picked. Click on the issues
    section. Filter search bar would display *is:issue is:open*
    Just add *label:2018-Open* in the filters
    search bar. Look through the displayed issues and pick any issue with [[https://help.github.com/articles/about-labels/][labels]] *label:2018-Open*.
  + Step 4 - Start making the code changes in the
    forked repository to resolve the selected issue/bug.
  + Step 5 - Test the issue with the changed functionality. 
  + Step 6 - Push the code and [[https://docs.google.com/presentation/d/1HlGjkacVdE7-3FRc8x8RKEUJiTmfnrxqe8BX4ZjnSNI/edit?usp=sharing][commit]] the code changes in
    the forked repository.
  + Step 7 - For every fixed issue create a pull request.
  + Step 8 - To create a pull request click on pull request
    in your repository. Click on *New pull request*. Then
    you will see *Comparing changes*. basefork:<<lab name
    that you have picked >>
  + Step 9 - After you create the pull request, update the issue that you have fixed
    with *commit id* of the code changes for which you created a pull
    request. Comment on the issue as *fixed*.
  + Step 10 - Once the issue has the comment as *fixed* , provide the issue
    link on Slack channel and request for validation.
Note to Mrudvika - Are they aware of the slack channel ?

* Steps for the validating an issue
  + Step 1 - Every fixed issue/bug
    should be validated by 2 members. Validators should be from different colleges
    and not from the same college as the student fixing the issue. Both the
    validator must review the fixes and respond on the
    same issue with the comment that the *issue fix is
    correct*.  
  + Step 2 - As a validator, you can pick fixed issues from the Slack channel.
    Make sure that it has not been already validated by going through the 
    comments in the issues.
  + Step 3 - Once you test the fix by throughly testing it, you should add a comment 
    in the issue as *Validated - 1* or *Validated-2* depending upon whether you are
    the first or the second validator.
  
 * Lifecycle of a fixed and validated issue 
  + Step 1 - Once a fixed issue gets reviewed and validated by the 2
    validators, the Virtual Labs team would review the fix for the
    final acceptance. If the issue fix is accepted by the Virtual Labs
    team also then  you would see the comment *Fix is validated
    and ready for production*. 
  + Step 2 - If you see the comment as *Fix is validated
    and ready for production* in any issue consider that the
    issue has been fixed and no more fixes would be accepted. 
  + Step 3 - Do not pick issues which have label as resolved 
    (label:resolved).

  The last date for fixing/validating issues/bugs is 10th November, 2018.

* Selection Criteria
  The following will be considered in the internship
  selection process
  - Number of issues fixed.
  - Number of issues validated.
  - Type of issues resolved.
* Conclusion
  After the validation process, the issues would be considered as
  resolved and moved to production.

