#+TITLE: Phase 2 : Fixing and Validation of issues in Virtual Labs
#+AUTHOR: VLEAD
#+DATE: [2018-04-25 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the process to be followed by the
  interested students who wish to work for Virtual Labs
  remotr internship and contribute to the open source
  community like GitHub.
* Process
  The Phase2 of the internship includes 2 parts.
  + Part 1 : Fixing the issues/bugs in the [[https://github.com/virtual-labs/][Virtual Labs]]
    repository.
  + Part 2 : Validating the fixed issue.

* Link for lab code repositories
  Please use this [[https://github.com/virtual-labs/][link]] for the IIIT-Hyderabad lab code
  repositories for the issues. The IIIT hyderabad labs which
  needs to be fixed would have a naming convention of
  <labname>-iiith. Please go through all the repos existing
  here. You are free to pick up any issues to fix. 

* Steps to be followed for fixing issues.
  + Step 1 - Choose a lab for which you want to start
    resolving the issues. Select the lab repository from
    [[https://github.com/virtual-labs/][Virtual Labs]].
  + Step 2 - [[https://help.github.com/articles/fork-a-repo/][Fork]] the lab repository so that you have the
    local copy of the lab codebase in your machine.
  + Step 3 - Go back to the main repository of the Virual
    Labs you  have picked. Click on the issues
    section. Filter search bar has *is:issue is:open*
    already just paste *label:2018-Open* in the filters
    search bar. Now you can pick any issues with [[https://help.github.com/articles/about-labels/][labels]]
    *label:2018-Open* and can start resolving the issues.
  + Step 4 - Now you can start doing the code changes in the
    forked repository and resolve the issues/bugs.
  + Step 5 - Test the issue with the changed functionality. 
  + Step 6 - Push the code and [[https://docs.google.com/presentation/d/1HlGjkacVdE7-3FRc8x8RKEUJiTmfnrxqe8BX4ZjnSNI/edit?usp=sharing][commit]] the code changes in
    the forked repository.
  + Step 7 - For every fixed issue create a pull request.
  + Step 8 - To create a pull request click on pull request
    in your repository. Click on *New pull request*. Then
    you will see *Comparing changes*. basefork:<<lab name
    that you have picked >>
  + Step 9 - After you create the pull request, update the same issue
    with *commit id* of the code changes for which you created a pull
    request. Comment on the issue as *fixed*.
  + Step 10 - Once the issue has comment as *fixed* , provide the issue
    link on Slack channel for the validation process.

* Steps for the validation process
  + Step 1 - In the validation process fixed issued/buugs
    should be validated by 2 members. Among which one
    validator could be from the same college but the other
    validator must be from some other college. Both the
    validators must also review the fixes and respond on the
    same issue with the comment that the *issue fix is
    correct*.  
  + Step 2 - Once the issue gets reviewed and approved by the 2
    validators, the Virtual Labs team would review the fix for the
    final acceptance. If the issue fix is accepted by the Virtual Labs
    team also then  you would see the comment *Fix is validated
    and ready for production*. 
  + Step 3 - After you see the comment as *Fix is validated
    and ready for production* and more than one student was
    working on the issue simultaneously, consider that the
    issue is fixed no more fixes would be accepted by any
    other student.
  + Step 4 - Switch to some other issue when you see an issue labelled
    as *resolved*. It would still not be marked as *closed* because it
    would be undergoing the deployment testing by the Virtual Labs
    team.

    This is an iterative cycle and it goes on till the end of the
    marked period for all the selected students. This marked period is
    till 10th November, 2018.

* Selection Criteria
  The following will be considered in the internship
  selection process
  - Number of issues fixed.
  - Number of issues validated.
  - Type of issues resolved.
* Conclusion
  After the validation process, the issues would be considered as
  resolved and moved to production.

