#+TITLE: Phase 1 : Understanding Virtual Labs 
#+AUTHOR: VLEAD
#+DATE: [2018-04-25 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the process to be followed by the
  students who registered for Virtual Labs remote internship
  and also interested in contributing to the open source
  community like GitHub.

* Process
  The process of internship is segregated in 3 phase.
  + Phase 1 : In this phase feedback forms are sent to the
    students. They were asked to browse 10 IIIT-H
    experiments and fill the feedback form and return to
    us. Based on the feedback form sent the students will be
    shortlisted and selected for phase 2.
  + Phase 2 : In this phase students will be fixing the bugs
    in GitHub of Virtual Labs. The detailed steps are
    explained elaborately below. Once you meet the selection
    criteria in phase 1. You will be selected as intern and
    would be moved to phase 2 of the outreach remote
    internship.
  + Phase 3 : Selected interns will be working conversion of
    experiments adobe flash, Java3D to JavaScript and
    building new experiments for Virtual Labs.

* Prerequisites 
  + Download the feedback form from the [[https://drive.google.com/file/d/1FBkH8uMY8OgdNLUw4laE6kn6i0Q5hjeI/view?usp=sharing][link]]. 
  + The following are the required software installations.
    + [[http://get.adobe.com/flashplayer/][Adobe Flash]]
    + [[https://www.java.com/en/download/help/windows_manual_download.xml][Java]] (Click on "Download and Install")
    + [[http://download.oracle.com/otn-pub/java/java3d/1.5.1/java3d-1_5_1-windows-amd64.exe][Java3d]] (Package: j3d-1_5_2-linux-amd64)
  
* Steps to be followed for browsing the labs in Virtual Labs
  + Step 1 - Open your Web Browser. Type http://vlab.co.in/
    and press Enter (or) Click [[http://vlab.co.in/][here]] This will be redirect
    you Virtual Labs website.
  + Step 2 - Scroll the page down. You will be able to see
    "Broad Areas of Virtual Labs".
  + Step 3 - Click on any Discipline/Branch you belong to.
    For Example : "Computer Science & Engineering"
  + Step 4 - Now you will be able to see the labs related to
    the discipline selected in Step 3.  
  + Step 5 - Click any lab you wish to perform, that takes
    you to the Experiment page.  
    For Example : Click on "Data Structures"
  + Step 6 : Click on "List of experiments" in the left menu
    bar. This takes you to the list of experiments page.
  + Step 7 - Click on any experiment. It will redirects you
    the Introduction of respective experiment. 
    For Example : Click on "Sorting using Arrays"  
  + Step 8 - To perform any experiment, Click on
    "Simulation/Experiment". Now you can start performing
    the experiments of Virtual Labs.  
    For example : Click on "Quick Sort". The experiment
    opens in new window. In case if your not able to access
    please make sure that Adobe flash is installed and
    allowed for the web Browser.
  + Step 9 - After Performing the experiment, make sure that
    you note the experiment name in the feedback form
    document. 
  + Step 10 - You need to perform atleast 15 experiments
    of any labs and note them in the feedback form
    document. 
  + Step 11 - Make sure that you answer 4 questions on the
    feedback form.
  + Step 12 - Please fill in your motivation or interest in
    doing the experiments in the Virtual Lab, before you
    start the experiment, then after 5, after 10 and
    after 15. Rate your motivation or interest on a scale of
    1 to 10.
 
* Submit the feedback form
  + Step 1 - Fill the feedback form (2 Pages) document.
  + Step 2 - Attest the signature in a paper.
  + Step 3 - Scan the feedback form and signature
    documents. 
  *Note*: You can scan through Android applications like
    CamScanner etc.,
  + Step 4 - Click the [[https://docs.google.com/forms/d/e/1FAIpQLSeKq20ij9C7fjxqY7giIu3h2jEhGQiLYImS3nQob-Pyq6O58g/viewform][form]] to submit your feedback form.

* Conclusion
  After the receiving of the feedback forms, Shortlisting of
  students will be done. The deadline for submitting the
  feedback form is *05 October, 2018*.

