#+TITLE: Phase 1 : Exploring Virtual Labs 
#+AUTHOR: VLEAD
#+DATE: [2018-04-25 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the process to be followed by the
  students who registered for Virtual Labs remote internship
  and also interested in contributing to the open source
  community like GitHub.

* Process
  The process of internship is segregated in 3 phase.
  + Phase 1 : In this phase feedback forms are sent to the
    students. They were asked to browse 10 IIIT-H
    experiments and fill the feedback form and return to
    us. Based on the feedback form sent the students will be
    shortlisted and selected for phase 2.
  + Phase 2 : In this phase students will be fixing the bugs
    in GitHub of Virtual Labs. The detailed steps are
    explained elaborately below. Once you meet the selection
    criteria in phase 1. You will be selected as intern and
    would be moved to phase 2 of the outreach remote
    internship.
  + Phase 3 : Selected interns will be working conversion of
    experiments adobe flash, Java3D to JavaScript and
    building new experiments for Virtual Labs.

* Prerequisites 
  + Download the feedback form from the [[https://drive.google.com/file/d/1Ss1GRPb5N74-1shuT-L8QdBnYn_O3jE_/view][link]]. 
  + The following are the required software installations.
    + [[http://get.adobe.com/flashplayer/][Adobe Flash]]
    + [[https://www.java.com/en/download/help/windows_manual_download.xml][Java]] (Click on "Download and Install")
    + [[http://download.oracle.com/otn-pub/java/java3d/1.5.1/java3d-1_5_1-windows-amd64.exe][Java3d]] (Package: j3d-1_5_2-linux-amd64)
  
* Steps to be followed for browsing the labs in Virtual Labs
  + Step 1 - Open your Web Browser. Type
    http://iiith.vlabs.ac.in/ and press Enter (or) Click
    [[http://iiith.vlabs.ac.in/][here]]. This will be redirect you Virtual Labs IIITH  website.
  + Step 2 - Click on "Labs" menu on the menu bar/header.
  + Step 3 - Hover on other disciplines and click on your
    respective discipline/branch.
  + Step 4 - Step 3 takes you to the list of labs of the
    selected discipline/branch.  
  + Step 5 - Click any lab you wish to perform that takes
    you to the Experiment page. Click on "Experiments/List
    of experiments" in the left menu bar. This takes you to
    the list of experiments page.
  + Step 6 - Click on any experiment. It will redirects you
    the Introduction of respective experiment. 
  + Step 7 - To perform any experiment, Click on
    "Simulation/Experiment" and you can start performing the
    experiments of Virtual Labs.
  + Step 8 - After Performing the experiment, make sure that
    you note the experiment name in the feedback form
    document. 
  + Step 9 - You need to perform atleast 10-15 experiments
    of any labs and note them in the feedback form
    document. 
  + Step 10 - Make sure that you answer 4 questions on the
    feedback form.
 
* Submit the feedback form
  + Step 1 - Fill the feedback form (2 Pages) document.
  + Step 2 - Attest the signature in a paper.
  + Step 3 - Scan the feedback form and signature
    documents. 
  Note: you can scan through Android applications like
    CamScanner etc.,
  + Step 4 - Click the [[https://docs.google.com/forms/d/e/1FAIpQLSeKq20ij9C7fjxqY7giIu3h2jEhGQiLYImS3nQob-Pyq6O58g/viewform][form]] to submit your feedback form.

* Conclusion
  After the receiving of the feedback forms, Shortlisting of
  students will be done. The deadline for submitting the
  feedback form is 05 October, 2018.

