#+TITLE: Manual for Students
#+AUTHOR: VLEAD
#+DATE: [2018-04-12 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction - Issue/bug/defect/enhancement process
  This document describes the detailed steps to be followed by the
  students to participate in the Virtual Labs internship program.

* Steps to be followed for raising issues/bugs/defects/enhancements
** Step 1
   Create a new gitlab project
   1) Create a GitLab username which is also called as
      GitLab handle.
   2) Create a new GitLab project.
      - Steps to create a new gitlab project
        1) Login to your gitlab profile using the handlers
          and click on New Projects.
        2) Name your project as
           "*virtual-labs-internship-<your name>*". 
        3) Set the 'Visibility Level' as *Private*.
        4) Click on 'Create Project'.
        5) Click on "Settings" from slider bar that is on
           the left side of your web page. Then click on
           "Members" option from the settings menu.
        6) Select "*outreach-internship*" in "Select
           members to invite" section. 
        7) Select "master" for "Choose a role permission"
           field.
        8) Click on "*Add to project*".

** Step 2
  1) Go to the [[www.http://vlabs.ac.in][Virtual Labs website]] and click on
     IIIT-Hyderabad institute available in the Participating 
     institute in the left corner of the webpage to access
     the labs to be tested.
  2) Select a lab and start exploring the features of the
     experiments and the content
  3) While exploring the lab ,you may encounter the issues
     such as
   1) *Operational defects* : Such as broken links, error
      pages, invisible or incorrect content including
      English grammar and buttons that not in
      functioning. The defects that you have observed other
      than the above listed are also be logged as bugs. 
   2) *Simulation defects* :
       + The simulation that doesnot work as per the given
         instructions.
       + The simulator with no instructions.
       + When the output of the simulation is not as per the
         requirement.
       + Logical flaws in the experiment's simulation.
       + Quality of simulator can be improved or enhanced.
  4) Log as issues in gitlab
   
** Step 3 
   Logging issues in GitLab
   1) The issues need to be logged in the project that you
      have created. Please follow the steps given below to
      create a new issue in Gitlab.
   2) Click on "Issues" option, that is just below the
      overview on the left hand side of your web page.
   3) Click on "New Issue".  
   4) Title of the issue should be in the following format.
      "*<lab_name>_<experiment_name>_<sub section of
      experiment where the bug is detected>*"
      - For Example :
        problem-solving_numerical-representation_objective
   5) Following information must be given in the issues
      while raising a bug in Gitlab.
    + Defect description : The description should specify an
      exact problem in the application. 
    + Steps to reproduce the issue : A detailed step by step
      description to be given right from the login step
      until the bug is identified.
    + Expected result : It should elaborate the result which
      you are expecting to see as an end user.
    + Actual result : This section should descibe what the
      feature is actually showing instead of correct results.
    + Screen shot : A small screenshot of the defect
      capturing the screen where it was identified and needs
      to be resolved.
    Please go through this [[https://github.com/virtual-labs/problem-solving-iiith/issues/343][Sample Issue]] for better understanding. 

** Step 4 
   Labels are added for better identity and also to
   categorize the issues
   1) Category : At any time an issue could be either of the
      two -
      + *Bug* - This label refers to the existing problem in the
        labs related to  section/sub section.
      + *Enhancement* - This label refers to new suggestions for the
        labs which could improve the lab quality.
   2) Type of issues :
      An issue should only be in any one of the types 
      + *Content* - This label refers to the content which is not
        comprehensible or has some mistakes, otherwise a new content
        needs to be added in case of incomplete information.    
      + *Functionality* - This label refers to the issues where the
        features are not working. Any user interface related problems
        like broken links or buttons not functioning would also be
        labelled as Functionality.
   
** Step 5         
  The following mentioned issues would be considered invalid
   1) The Feedback submit is not working across all the labs and
      experiments, this is again a known issue to us. It won't be
      considered as valid.
   2) We are not focussing on spelling mistakes and
      grammatical errors, even if such issues are raised
      they won't be given much weightage.

* Time limit for raising issues
   The students are allowed to log defects till *30th May*
   2018, 08:00 A.M. IST.
   
* Perks and Prize money
   Top 10 students would be awarded with prizes based on the
   gravity of issues (severity level, functionality defects
   identified, proposal for enhancements and logical flaws)
   identified/logged after the validation and reviewing
   process.
